# Generated by Django 4.0.4 on 2023-05-19 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrada')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveBigIntegerField(default=0, verbose_name='Edad')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Salario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
